In [ ]:
REPOSITORY NUMPY

Table of Contents

Array creation

ND Arrays

Numpy array initialization
  arange
  Zeros
  Ones
  Linspace
  eye
    
Array initialization using random values

Conditional array access

View vs Copy vs reshape vs slice vs split

Array operation

Array broadcasting
 
Shape manipulation
  Merging 
  Splitting
      Hsplit
      Vsplit
       split

I/O

In [1]:
#imorting pandas and numpy for data frame and various calcuation to help in EDA
import numpy as np
import pandas as pd

#importing packages for visulaisation
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

#to get to see graphs in out put this line is mandatory in python
%matplotlib inline

#pip installing pandas for pandas profiling
!pip install pandas-profiling

In [ ]:
# 'ARRAY CREATION METHODS'

In [3]:
# Python program to create 
# an array
 
# Creating an array using list
arr=[1, 2, 3, 4, 5]
for i in arr:
    print(i)

1
2
3
4
5


In [18]:
# array using numpy.empty
# numpy.empty(shape, dtype = int, order = 'C') - code used
# Example:
x = np.empty([2,3], dtype = int) 
print(x)

[[-1898060096          92           0]
 [          0           1           0]]


In [21]:
# numpy.empty(shape, dtype = float, order = 'C') - code used
# Example:
x = np.empty([2,3], dtype = float) 
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# array using numpy.zeros
# Example:

# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print(x)

[0. 0. 0. 0. 0.]


In [24]:
import numpy as np 
x = np.zeros((5,), dtype = np.int) 
print(x)

[0 0 0 0 0]


In [9]:
# custom type 
import numpy as np 
x = np.zeros((2,2))  
print(x)

[[0. 0.]
 [0. 0.]]


In [29]:
# array using numpy.ones
# Example:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print(x)

[1. 1. 1. 1. 1.]


In [31]:
x = np.ones([2,2], dtype = int) 
print(x)

[[1 1]
 [1 1]]


In [ ]:
# 'ND ARRAYS'

In [4]:
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [5]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


In [6]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [7]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
# NumPy Eye array example

array1 = np.eye(3, dtype=int)
print(array1)
 
array2 = np.eye(5, k=2)
print(array2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# NUMPY ARRAY WITH SHAPE

In [12]:
# Create a 1D Numpy Array of length 10 & all elements initialized with value 5

arr = np.full(10, 5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [14]:
#Create a 2D Numpy Array of 4 rows & 5 columns. All intialized with value 7
arr = np.full((4,5), 2)
print(arr)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [16]:
# Create a 3D Numpy array & all elements initialized with value 8
arr = np.full((2,4,5), 2)
print(arr)

[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]]


In [9]:
np.linspace(0,100,5) 

array([  0.,  25.,  50.,  75., 100.])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
Takeaways

•numpy.linspace() returns evenly spaced numbers over a specified interval

•numpy.eye is used to generate an identity matrix

•numpy.zeros generates a matrix with all elements 0.
 So, as you can see there are many built in function in numpy each faciliating 
performing vaious mathematical operations on different types of data.

In [13]:
# 1.6. Array Initialization using Random Numbers

# Generate an array of 5 random numbers
np.random.rand(10)

array([0.39075225, 0.00376918, 0.11215938, 0.00102133, 0.6495003 ,
       0.69722664, 0.34070791, 0.77302049, 0.46728681, 0.20429467])

In [14]:
# Generate a 2D matrix where elements are random
np.random.rand(2,2)

array([[0.02227415, 0.31770351],
       [0.08072313, 0.1245215 ]])

In [15]:
# Generate a 4*4 matrix where the elements are distributed in random distribition.

np.random.randn(4,4)

array([[-0.13560394,  1.84086746, -1.41019671,  0.42523149],
       [ 0.07007448, -1.09519179,  0.40914049, -1.73047927],
       [-2.8861851 , -0.9551733 ,  1.4275448 , -1.21111933],
       [ 1.34182362,  1.4463321 ,  0.18608107, -0.05054114]])

In [16]:
# Generate a random array of 9 elements and convert it into 3*3 matrix using reshape

nine_random_values = np.random.rand(9)
print(nine_random_values)

[0.63327493 0.38288697 0.30318319 0.6612482  0.19821935 0.41229793
 0.5317664  0.7729559  0.17151814]


In [17]:
nine_random_values.reshape(3,3)

array([[0.63327493, 0.38288697, 0.30318319],
       [0.6612482 , 0.19821935, 0.41229793],
       [0.5317664 , 0.7729559 , 0.17151814]])

In [5]:
# VIEW VS COPY VS RESHAPE VS SLICE VS SPLIT

# View or Shallow Copy

# To begin with, a is 3X2 array 
a = np.arange(6).reshape(3,2) 

print('Array a:')
print(a) 

print ('Create view of a:')
b = a.view() 
print (b)  

print ('id for both the arrays are different:')
print ('id of a:')
print (id(a))
print ('id of b:')
print (id(b))

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

print ('Shape of b:')
print (b)  

print ('Shape of a:') 
print (a)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id for both the arrays are different:
id of a:
362237844176
id of b:
362237844736
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]


In [6]:
#Slice of an array creates a view.

a = np.array([[10,10], [2,3], [4,5]]) 

print ('Our array is:' )
print (a)  

print ('Create a slice:' )
s = a[:, :2] 
print (s) 

Our array is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a slice:
[[10 10]
 [ 2  3]
 [ 4  5]]


In [7]:
# Deep Copy

a = np.array([[10,10], [2,3], [4,5]]) 

print ('Array a is:')
print (a)  

print ('Create a deep copy of a:')
b = a.copy() 
print ('Array b is:')
print (b) 

#b does not share any memory of a 
print ('Can we write b is a')
print (b is a)

print ('Change the contents of b:')
b[0,0] = 100 

print ('Modified array b:')
print (b)  

print ('a remains unchanged:')
print (a)

Array a is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a deep copy of a:
Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Can we write b is a
False
Change the contents of b:
Modified array b:
[[100  10]
 [  2   3]
 [  4   5]]
a remains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]


In [9]:
# RESHAPE in NUMPY

a = np.arange(8)
print ('The original array:')
print (a)
print ('\n')

b = a.reshape(4,2)
print ('The modified array:')
print (b)

The original array:
[0 1 2 3 4 5 6 7]


The modified array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [10]:
# SLICE in NUMPY

a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [11]:
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [12]:
# slice single item

a = np.arange(10) 
b = a[5] 
print (b)

5


In [13]:
# slice items starting from index 

a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [14]:
# slice items between indexes 
 
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [16]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)

# slice items starting from index

print ('Now we will slice the array from the index a[1:]')
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [17]:
# array to begin with 

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:')
print (a) 

# this returns array of items in the second column 
print ('The items in the second column are:')
print (a[...,1])

# Now we will slice all items from the second row 
print ('The items in the second row are:')
print (a[1,...])  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:')
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
The items in the second column are:
[2 4 5]
The items in the second row are:
[3 4 5]
The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [4]:
# SPLITTING AND MERGING in NUMPY

arr_x = np.array([[1,2,3,4],[5,6,7,8]])                
arr_y = np.array([[21,22,23,24],[25,26,27,28]])

In [5]:
arr_x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr_y

array([[21, 22, 23, 24],
       [25, 26, 27, 28]])

In [7]:
# Concatenate is used to join 2 arrays either along rows or columns

np.concatenate((arr_x, arr_y), axis=1)

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28]])

In [8]:
arr_z = np.concatenate((arr_x, arr_y), axis=0)
arr_z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [9]:
# Horizontal Split using hsplit

print(arr_x)
print()
print(arr_y)
print()
print(arr_z)

[[1 2 3 4]
 [5 6 7 8]]

[[21 22 23 24]
 [25 26 27 28]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]


In [10]:
np.hsplit(arr_z, 2)

[array([[ 1,  2],
        [ 5,  6],
        [21, 22],
        [25, 26]]), array([[ 3,  4],
        [ 7,  8],
        [23, 24],
        [27, 28]])]

In [11]:
# Vertical Split using vsplit

np.vsplit(arr_z, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[21, 22, 23, 24],
        [25, 26, 27, 28]])]

In [12]:
# Numpy Array Operations

# Numpy Broadcasting

arr_2d = np.array([[1,2,3],[5,6,7],[8,9,10],[12,13,14]])
arr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [12, 13, 14]])

In [13]:
arr_2d.shape

(4, 3)

In [14]:
scaler = 3

In [15]:
scaler

3

In [16]:
arr_2d +  3

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13],
       [15, 16, 17]])

In [17]:
arr_1d = np.array([10,10,10])
arr_1d.shape

(3,)

In [18]:
print(arr_1d)
print()
print()
print(arr_2d)

[10 10 10]


[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]]


In [19]:
arr_2d + arr_1d

array([[11, 12, 13],
       [15, 16, 17],
       [18, 19, 20],
       [22, 23, 24]])

In [20]:
arr = np.array([[1,1,1,1]])

In [21]:
print(arr)
print()
print()
print(arr_2d)

[[1 1 1 1]]


[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]]


In [3]:
# Numpy Mathematical Functions

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr[0]=2

In [25]:
# Numpy Mathematical Functions

arr

array([ 2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr.min()

2

In [27]:
arr.max() 

10

In [28]:
a = [5,2,3,4,1]
#a.min()
min(a)
#max(a)

1

In [29]:
min(arr)

2

In [30]:
arr.argmin()

0

In [31]:
arr.argmax()

9

In [4]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [5]:
arr.mean()

5.5

In [6]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [7]:
# I/O in Nmumpy examples

a = np.array([1,2,3,4,5]) 
np.save('outfile',a)

In [8]:
b = np.load('outfile.npy') 
print(b)

[1 2 3 4 5]


In [10]:
a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print(b)

[1. 2. 3. 4. 5.]
